root: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended

env:
  node: true
  browser: true

plugins:
  - import
  - '@typescript-eslint'
  - react
  - prettier

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: detect

rules:
  '@typescript-eslint/ban-types':
    - error
    - types:
        '{}': false
        Function: false
        extend-defaults: true

  '@typescript-eslint/no-explicit-any':
    - off

  '@typescript-eslint/no-unused-vars':
    - warn
    - vars: all
      args: after-used
      ignoreRestSiblings: false
      argsIgnorePattern: ^_

  import/order:
    - warn
    - groups:
        - - builtin
          - external
        - - parent
          - sibling
          - index
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true

  no-unused-vars:
    - off

  prettier/prettier:
    - error
    - {}
    - usePrettierrc: true

  react/react-in-jsx-scope:
    - off
